#!/bin/bash

# Vercel Environment Variables Setup Script
echo "Setting up Vercel environment variables..."

# The DATABASE_URL to add
DATABASE_URL="postgresql://neondb_owner:npg_Or5q0LHdgsFj@ep-wandering-dawn-adwq3tpf-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require"

echo ""
echo "To add the DATABASE_URL to Vercel, you have two options:"
echo ""
echo "OPTION 1: Using Vercel CLI (Recommended)"
echo "========================================="
echo "1. First login to Vercel:"
echo "   vercel login"
echo ""
echo "2. Then add the environment variable:"
echo "   echo '$DATABASE_URL' | vercel env add DATABASE_URL production"
echo "   echo '$DATABASE_URL' | vercel env add DATABASE_URL preview"
echo "   echo '$DATABASE_URL' | vercel env add DATABASE_URL development"
echo ""
echo "3. Pull the environment variables locally:"
echo "   vercel env pull .env.development.local"
echo ""
echo "4. Trigger a new deployment:"
echo "   vercel --prod"
echo ""
echo "OPTION 2: Manual via Dashboard"
echo "==============================="
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Select your project: test-spec-kit-project"
echo "3. Go to Settings → Environment Variables"
echo "4. Add new variable:"
echo "   Name: DATABASE_URL"
echo "   Value: $DATABASE_URL"
echo "   Environment: Select all (Production, Preview, Development)"
echo "5. Click Save"
echo "6. Redeploy from the Deployments tab"
echo ""
echo "DATABASE_URL to copy:"
echo "$DATABASE_URL"